// <auto-generated />
using System;
using Associado.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;


namespace Associado.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Associado.Domain.Associad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ceep");

                    b.Property<string>("cidade");

                    b.Property<string>("cpf");

                    b.Property<string>("descProblema");

                    b.Property<string>("email");

                    b.Property<string>("endereco");

                    b.Property<string>("nome");

                    b.Property<string>("uf");

                    b.HasKey("id");

                    b.ToTable("Associado");
                });

            modelBuilder.Entity("Associado.Domain.AssociadoDTO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ceep");

                    b.Property<string>("descProblema");

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("AssociadoDTO");
                });

            modelBuilder.Entity("Associado.Domain.Dependente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Associadid");

                    b.Property<string>("grau");

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.HasIndex("Associadid");

                    b.ToTable("Dependente");
                });

            modelBuilder.Entity("Associado.Domain.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("login");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Associado.Domain.Dependente", b =>
                {
                    b.HasOne("Associado.Domain.Associad")
                        .WithMany("dependente")
                        .HasForeignKey("Associadid");
                });
#pragma warning restore 612, 618
        }
    }
}
